# Generated by Django 5.0.3 on 2024-03-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bet_maker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='status',
            field=models.CharField(choices=[('pending', 'Ещё не сыграла'), ('won', 'Выиграла'), ('lost', 'Проиграла')], default='pending', max_length=10),
        ),
    ]
