# Generated by Django 5.0.3 on 2024-03-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bet_maker', '0002_bet_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Ещё не сыграла'), ('WON', 'Выиграла'), ('LOST', 'Проиграла')], max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Bet',
        ),
    ]
